const Constants = {
    MEMORYTASK_MILLIS: 800,
    VERIFICATION_MILLIS: 7000,
    LEFTBUTTON_TITLE: 'True',
    RIGHTBUTTON_TITLE: 'False',
    LEFTBUTTON_VALUE: 1,
    RIGHTBUTTON_VALUE: 0,
    TIMEOUT_VALUE: 999,
    RECALLBUTTON_ROW_LENGTH: 3
};

export default Constants;